/**
 * Generate the UMD/IIFE variant from the ES module, so a plain `<script>` tag
 * works without a bundler. The transform is a whitespace-preserving strip of
 * the `export` keywords; there is no compilation and no dependency.
 *
 * Usage: `node build-umd.mjs` (writes sidecartunnel.umd.js)
 *        `node build-umd.mjs --check` (exit 1 if the committed file is stale)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const SRC = join(HERE, 'sidecartunnel.js');
const OUT = join(HERE, 'sidecartunnel.umd.js');
const EXPORTS = ['connect', 'backoffDelay', 'clampRetryAfter', 'MAX_RETRY_AFTER_MS', 'resolveUrl', 'StError'];

/**
 * Build the UMD source text from the ES module source text.
 *
 * @param {string} esm Contents of sidecartunnel.js.
 * @returns {string} Contents of sidecartunnel.umd.js.
 */
export function toUmd(esm) {
  const body = esm
    .replace(/^export default [\s\S]*?;\s*$/m, '')
    .replace(/^export (class|function|const|let) /gm, '$1 ')
    .trim();
  return `// GENERATED by build-umd.mjs from sidecartunnel.js — do not edit.
(function (root, factory) {
  if (typeof exports === 'object' && typeof module !== 'undefined') { module.exports = factory(); }
  else if (typeof define === 'function' && define.amd) { define([], factory); }
  else { root.sidecartunnel = factory(); }
})(typeof self !== 'undefined' ? self : globalThis, function () {
'use strict';

${body}

return { ${EXPORTS.join(', ')} };
});
`;
}

const umd = toUmd(readFileSync(SRC, 'utf8'));
if (process.argv.includes('--check')) {
  const current = (() => { try { return readFileSync(OUT, 'utf8'); } catch { return null; } })();
  if (current !== umd) { console.error('sidecartunnel.umd.js is stale — run `node build-umd.mjs`'); process.exit(1); }
  console.log('sidecartunnel.umd.js is up to date');
} else {
  writeFileSync(OUT, umd);
  console.log(`wrote ${OUT}`);
}
